FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

WORKDIR /app

# cài python
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# alias python
RUN ln -s /usr/bin/python3 /usr/bin/python

COPY requirements-gpu.txt .

RUN pip install --no-cache-dir -r requirements-gpu.txt

COPY . .

RUN mkdir -p logs

EXPOSE 8000

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]