FROM python:3.12-slim

WORKDIR /yolo

# system dependencies cho opencv
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# copy requirements trước để cache
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copy source code
COPY app ./app

# tạo logs folder
RUN mkdir -p logs

EXPOSE 8000

CMD ["uvicorn", "app.src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]